# Generated by Django 5.2.3 on 2025-06-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsquery',
            name='ip_address',
        ),
    ]
